kind: pipeline
type: docker
name: default

steps:
- name: tests
  image: alpine
  commands:
  - yarn install
  - yarn test

- name: lint
  image: alpine
  commands:
  - yarn install
  - yarn lint

- name: complete
  image: alpine
  commands:
  - echo done
  - echo world
  depends_on:
  - tests
  - lint
