kind: pipeline
type: docker
name: go-tests

steps:
- name: tests
  image: golang
  commands:
  - go install .
  - go test -v ./...
  when:
    event:
      - pull_request

---

kind: pipeline
type: docker
name: js-unit-tests

steps:
- name: jest
  image: node
  commands:
  - yarn install
  - yarn test -t='^(?!.*?@slow)' --silent
  when:
    event:
      - pull_request

---

kind: pipeline
type: docker
name: js-slow-unit-tests

steps:
- name: jest
  image: node
  commands:
  - yarn install
  - yarn test -t='@slow' --silent
  when:
    event:
      - pull_request

---

kind: pipeline
type: docker
name: js-lint

steps:
- name: eslint
  image: node
  commands:
  - yarn install
  - yarn lint
  when:
    event:
      - pull_request
