kind: pipeline
type: docker
name: en

- name: tests
  image: node
  commands:
  - yarn install
  - yarn test

---

kind: pipeline
type: docker
name: fr

steps:
- name: lint
  image: node
  commands:
  - yarn install
  - yarn lint
