kind: pipeline
type: docker
name: go

steps:
- name: tests
  image: golang
  commands:
  - go install .
  - go test -v ./...

---
kind: pipeline
type: docker
name: tests

steps:
- name: jest
  image: node
  commands:
  - yarn install
  - yarn test

---

kind: pipeline
type: docker
name: lint

steps:
- name: eslint
  image: node
  commands:
  - yarn install
  - yarn lint
